[package]
name = "kalman-visualizer"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.33.2"
eframe = "0.33.2"
env_logger = "0.11.8"
log = "0.4.29"
nalgebra = "0.34.1"
egui_plot = "0.34.0"
assertables = "9.8.3"
glow = "0.16.0"
rand_distr = "0.5.1"
rand = "0.9.2"
